### ISSUE TITLE
gtklock-powerbar-module userswitch-command option missing

### ISSUE THREAD

**Issue by jovanlanik** [nwg-piotr/nwg-shell-config#28]
gtklock-powerbar-module has an option for calling the DM to switch users.
It has no default value is disabled as I don't want to assume which DM is being used (as far as I know nwg-shell also doesn't interact with the DM).
However I think it should still be available from the UI.

**Comment by nwg-piotr** [comment]
Finally, an option to log out (like exit sways session) would be of use, too.

**Comment by jovanlanik** [comment]
There is a logout-command option too. Also disabled by default.

**Comment by nwg-piotr** [comment]
Shit, I need to read docs one more time.

**Comment by jovanlanik** [comment]
https://github.com/jovanlanik/gtklock-powerbar-module/wiki lists all available options.

**Comment by nwg-piotr** [comment]
OK. It's gonna look something like this:

![image](https://user-images.githubusercontent.com/20579136/197362305-4485441e-877f-4d16-a603-628e40de8b9d.png)

![2022-10-22-230016_screenshot](https://user-images.githubusercontent.com/20579136/197362333-2132ef43-cc14-4bcb-9784-eddcfe82a8c9.png)
