### ISSUE TITLE
Not add second keyboard

### ISSUE THREAD

**Issue by tuxarch** [nwg-piotr/nwg-shell-config#3]
I can't add a second layout via nwg-shell-config, I added it via variables. That would be another output on the nwg-panel.
sway

**Comment by nwg-piotr** [comment]
Sorry, but I understand nothing. Could you be more specific?

**Comment by tuxarch** [comment]
Yes.
And if you don't mind, add the ability to display the current layout to nwg-panel.
Sorry for google translate.

**Comment by nwg-piotr** [comment]
No problem.

To see the layout, you may add a simple executor: `swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name'`.

**Comment by tuxarch** [comment]
Thank you. In my case
swaymsg -t get_inputs | jq '.[**1**].xkb_active_layout_name' | tr -d '"'
