### ISSUE TITLE
Allow disabling some parts

### ISSUE THREAD

**Issue by rs-pro0** [nwg-piotr/nwg-shell-config#42]
I want to keep my panel and notifications so it would be nice to have option to disable them or set your own command.

**Comment by nwg-piotr** [comment]
Just don't install the shell.

**Comment by rs-pro0** [comment]
I still want to use lock configuration so I’ll just implement it by myself

**Comment by nwg-piotr** [comment]
You're free to install the components you need, not all the shell.
