### ISSUE TITLE
What is point of switching alignment start/end and how to make additions look like rest of the app

### ISSUE THREAD

**Issue by rs-pro0** [nwg-piotr/nwg-shell-config#43]
So the title explains what I ask, but here is a screenshot of what I'm talking about now. Because I changed all alignments in the Notifications tab to START and this can break the design the way you imagined it.
![2023-04-28_23-24](https://user-images.githubusercontent.com/55341323/235247964-9ebf0884-15a2-41d2-b88a-75ec8b6f2f7a.png)

**Comment by nwg-piotr** [comment]
The layout of the fields in the form is a matter of taste. You can freely change it in your fork. Just remember that isolated changes have little chance of merging on my side.

**Comment by rs-pro0** [comment]
Yeah, this is why I want to make the design the same way as you did. I want it to be merged)
