### ISSUE TITLE
screenshot applet does not work with region (but screenshot script does)

### ISSUE THREAD

**Issue by Schievel1** [nwg-piotr/nwg-shell-config#62]
I have been trying to figure out what is going on here, it must be something simple, but I can't figure it out apparently. 
When I make a screenshot using the command `screenshot region` slurp gets started, I select a region and the screenshot gets saved in ~/Screenshots. Also I get the notification about that screenshot.

But if I click the screenshot applet in the panel and select "Region" slurp gets started as well, I select a region but the screenshot is no saved. (At least not in ~/Screenshots, maybe in some other place I don't know about.) And I also don't get a notification.

Using the applet I can make screenshots of the focused window and also fullscreen and display just fine. It only happens with region. 

Using grim and slurp on the command line like this `grim -g "$(slurp)" ~/Screenshots/test` also works fine.

**Comment by Schievel1** [comment]
I knew just when I open that issue it come to me. 
for the record: `screenshot region` and selecting region in the applet is not the same. Clicking region in the applet actually call `screenshot swappy`

**Comment by nwg-piotr** [comment]
Just install swappy.
