### ISSUE TITLE
Please add options to disable azote, and to disable or enable the hyprland splash text rendering

### ISSUE THREAD

**Issue by ethereal-engineer** [nwg-piotr/nwg-shell-config#71]
With the latest update of hyprland, the backgrounds have gone even beyond hyprchan (whom I loved anyway), and it would be a pity not to allow an option to see them when using nwg-shell. As for the splash text rendering, I really don't like having that but hyprland allows it to be turned off by a setting in misc. I already have my own sources doing this but I thought to mention it here for completeness.

**Comment by nwg-piotr** [comment]
https://github.com/nwg-piotr/nwg-shell-config/commit/d67d72eef20bec1d8bf6b1a5b886f945fc3c5daf

**Comment by nwg-piotr** [comment]
![obraz](https://github.com/nwg-piotr/nwg-shell-config/assets/20579136/75098dd8-faa2-4c81-9bdc-263e7b31a8a3)
