### ISSUE TITLE
No support for changing touchpad click_method.

### ISSUE THREAD

**Issue by yawor** [nwg-piotr/nwg-shell-config#79]
Hi,

Would it be possible to add support for changing input click_method for touchpad? The option takes one of 3 possible values:
- none
- button_areas (default) - left/middle/right mouse button click when pressing down the touchpad in specific areas (bottom left, middle and right by default)
- clickfinger - left/middle/right mouse button click when pressing down the touchpad with 1, 2 or 3 fingers

**Comment by nwg-piotr** [comment]
I see no relevant variable in [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Variables/) (?)

**Comment by yawor** [comment]
> I see no relevant variable in [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Variables/) (?)

It's in sway input config

**Comment by nwg-piotr** [comment]
Oh, I'm messing with the Hyprland-related part right now. I'll take a look at this a bit later.
