### ISSUE TITLE
nwg-shell-config 0.5.46-1: "Restore defaults" button fails to restore Hyprland settings

### ISSUE THREAD

**Issue by blauch** [nwg-piotr/nwg-shell-config#80]
**System Information:**

Operating System: Arch Linux 6.10.10-arch1-1
nwg-shell-config Version: 0.5.46-1
Hyprland Version: 0.43.0-1
Installation Method: nwg-iso

**Steps to Reproduce:**
* Launch nwg-shell-config.
* Navigate to Idle & Lock screen in the Common section.
* Click the "Restore defaults" button.
* Observe that settings, such as the Sleep Command, Resume-command, and After resume settings, are set to sway default settings

**Expected Behavior:**

I am running Hyprland and encountered a problem where the "Restore defaults" button within nwg-shell-config does not correctly restore the default settings for Hyprland. Upon clicking the "Restore defaults" button, I anticipate that all Hyprland settings would be reset to their default values. Yet it turns out that Sleep Command, Resume-command, and After resume settings are set to sway defaults

![image](https://github.com/user-attachments/assets/83da1eb6-ae2b-414b-8b1f-3768641171e0)

**Comment by nwg-piotr** [comment]
Actually we only have one default value on Hyprland: "systemctl suspend" for the sleep command. Restoring values appropriate for sway here is an error, of course. I'll fix it.
