### ISSUE TITLE
[Bug] Generated nwg-shell-config errors with Hyprland 0.45.0 

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-shell-config#84]
With the new Hyprland 0.45.0. Settings generated by shell-config gives config errors[^1]. Breaking changes are mentioned on the release note. [Hyprland 0.45.0 release](https://github.com/hyprwm/Hyprland/releases/tag/v0.45.0)

[^1]:![swappy-2024-11-12_181759](https://github.com/user-attachments/assets/71ef1cd8-10d1-4bd7-b98b-d4ccf2a68bc2)

**Comment by nwg-piotr** [comment]
You need to use v0.5.51: https://github.com/nwg-piotr/nwg-shell-config/releases/tag/v0.5.51

You'll also need to remove

```text
    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
```

from the main hyprland.conf file, or edit them according to comply with the latest Hyprland version.

**Comment by hecto600** [comment]
I'm already using nwg-shell-config 0.5.51 and rebooted the system, but includes.conf error persist. I would remove manually the lines from the file but idk what could happen. Do I need to do something beyond updating?
![swappy-2024-11-12_193953](https://github.com/user-attachments/assets/c53508d1-29b5-49c5-bf1d-6424ccd97b32)

**Comment by nwg-piotr** [comment]
Yo only need to run nwg-shell-config and press the Apply button, w/o changing anything.

**Comment by hecto600** [comment]
It is working now! Thanks ;)

**Comment by nwg-piotr** [comment]
You are welcome. :)
